services:
    z_admin.form.type.translatable:
        class: Alahtarin\TranslatableBundle\Form\Type\TranslatableRowType
        arguments: [@translator, %alahtarin_translatable.default_locales%]
        tags:
            - {name: form.type, alias: translatable}
